GET http://localhost:5233/todos/

###

POST http://localhost:5233/todos
Content-Type: application/json

{
    "id" : 3,
    "name" : "Three Demo",
    "dueDate" : "2025-06-21",
    "isCompleted" : false 
}

###

GET http://localhost:5233/todos/3

###

DELETE http://localhost:5233/todos/1

###
GET http://localhost:5233/tasks/1

